name: Deploy CloudFormation EC2-Instance
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::084828603933:role/EC2-CloudFormation-Role
          role-session-name: GitHubActionsSession
          aws-region: us-east-1
      
      - name: Test AWS Credentials
        run: aws sts get-caller-identity
      - name: Deploy IAM Role stack
        run: |
          aws cloudformation deploy \
            --template-file EC2Instance1.yml \
            --stack-name "GitHubActionsEC2Stack-${{ github.ref_name }}-${{ github.run_number }}" \
            --capabilities CAPABILITY_NAMED_IAM
